### ISSUE TITLE
System.InvalidOperationException on trying get mime message.

### ISSUE THREAD

**Issue by q00Dree** [danzuep/MailKitSimplified#11]
Hi @danzuep. I want to get `MimeMessage` while processing arrived message to get attachments and text from it and get error:

`System.InvalidOperationException: 'The ImapClient is currently busy processing a command in another thread. Lock the SyncRoot property to properly synchronize your threads.'`

Here's my code to reproduce:

```csharp
using MailKit;
using MailKitSimplified.Receiver.Services;

using var imapReceiver = ImapReceiver.Create("imapHost:imapPort")
    .SetCredential("login", "applicationPassword");

try
{
    await imapReceiver.ConnectAuthenticatedImapClientAsync();
    await imapReceiver.ConnectMailFolderAsync();

    await imapReceiver.MonitorFolder
       .SetMessageSummaryItems(MessageSummaryItems.Full | MessageSummaryItems.BodyStructure | MessageSummaryItems.UniqueId)
       .SetIgnoreExistingMailOnConnect(false)
       .OnMessageArrival(OnArrivalAsync)
       .IdleAsync();
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}

async Task OnArrivalAsync(IMessageSummary messageSummary)
{
    try
    {
        var mimeMessage = await imapReceiver.ReadMail.GetMimeMessageAsync(messageSummary.UniqueId);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
}
```

Or did I miss something and need to receive messages in a different way?

**Comment by q00Dree** [comment]
I recently saw a [ticket](https://github.com/jstedfast/MailKit/issues/1485) with the same error in the MailKit repository, maybe this will somehow help in solving the problem

**Comment by danzuep** [comment]
I've got a simple deep copy fix working for the idle client, but it won't work for `var mimeMessage = await messageSummary.GetMimeMessageAsync();` as that uses a readonly MailFolder assigned by MailKit in a Fetch function. I'll keep looking.

**Comment by q00Dree** [comment]
Oh, got you.
Thanks for samples. I keep several idle clients for different emails at the same time, so I have to create them without using DI.

**Comment by danzuep** [comment]
I got `await messageSummary.GetMimeMessageAsync();` working as well now in a new branch.

**Comment by danzuep** [comment]
Update to the latest version to get the fix.

**Comment by q00Dree** [comment]
Thank you for the quick solution. But I wonder, how it works in MailKit [ImapIdle](https://github.com/jstedfast/MailKit/tree/master/samples/ImapIdle) using one **ImapClient** for idling and fetching. Or I miss  something?

**Comment by q00Dree** [comment]
This code from sample works without any problem

```csharp
async Task FetchMessageSummariesAsync (bool print)
		{
			IList<IMessageSummary> fetched;

			do {
				try {
					// fetch summary information for messages that we don't already have
					int startIndex = messages.Count;

					fetched = client.Inbox.Fetch (startIndex, -1, request, cancel.Token);
					break;
				} catch (ImapProtocolException) {
					// protocol exceptions often result in the client getting disconnected
					await ReconnectAsync ();
				} catch (IOException) {
					// I/O exceptions always result in the client getting disconnected
					await ReconnectAsync ();
				}
			} while (true);

			foreach (var message in fetched) {
				if (print) {
					var mimeMessage = await client.Inbox.GetMessageAsync (message.UniqueId);
					Console.WriteLine ("{0}: new message: {1}", client.Inbox, mimeMessage.TextBody);
				}
				messages.Add (message);
			}
		}
```

**Comment by danzuep** [comment]
It's a good idea but it could raise some other issues.
1. It relies on exception handling to run, normally not a good practice.
2. If anyone tries to download the IMessageSummary returned using the internal IMailFolder it will throw another exception.

**Comment by danzuep** [comment]
> I keep several idle clients for different emails at the same time, so I have to create them without using DI.
This could be a good use-case for the Factory Method Design Pattern. Please let me know if you'd like to make one and submit a merge request.
