### ISSUE TITLE
Reconnect and reopen for _fetchReceiver and _fetchFolder

### ISSUE THREAD

**Issue by q00Dree** [danzuep/MailKitSimplified#13]
Hi. @danzuep. I checked your [bug fix](https://github.com/danzuep/MailKitSimplified/pull/12), but It seems to me **_fetchReceiver** and **_fetchFolder** need also reconnecting and reopening?

[This part of the code](https://github.com/danzuep/MailKitSimplified/blob/main/source/MailKitSimplified.Receiver/Services/MailFolderMonitor.cs#L289), it seems to me, may break if **_fetchReceiver** or **_fetchFolder** closes at some point.

**Comment by danzuep** [comment]
Thanks for highlighting that, I'll release a fix when I've got time later this weekend.

**Comment by danzuep** [comment]
Can you check the [13-Reconnect-IImapReceiver-and-IMailFolder_before-idle-fetch](https://github.com/danzuep/MailKitSimplified/tree/13-Reconnect-IImapReceiver-and-IMailFolder_before-idle-fetch) branch is working please?

**Comment by danzuep** [comment]
Should be good now but let me know if not.

**Comment by q00Dree** [comment]
Hm, I faced pretty strange behavior. I get messages with same **UniqueId** in **OnArrivalAsync** method. If I set **.SetIgnoreExistingMailOnConnect(false)** then messages that fall into the **OnArrivalAsync** method will have different **UniqueId**.  But when the method **.SetIgnoreExistingMailOnConnect(false)** completed and I start receiving new emails, their **UniqueId** become the same again.

Here's minimal code for reproduce:
```csharp
using MailKit;
using MailKitSimplified.Receiver.Services;
using Microsoft.Extensions.Logging;

using var loggerFactory = LoggerFactory.Create(_ => _.SetMinimumLevel(LogLevel.Trace).AddConsole());
var logger = loggerFactory.CreateLogger<Program>();

using var imapReceiver = ImapReceiver.Create("imapHost:imapPort")
    .SetCredential("login", "applicationPassword");

try
{
    await imapReceiver.ConnectAuthenticatedImapClientAsync();
    await imapReceiver.ConnectMailFolderAsync();

    await imapReceiver.MonitorFolder
       .SetMessageSummaryItems(MessageSummaryItems.Full | MessageSummaryItems.BodyStructure | MessageSummaryItems.UniqueId)
       .SetIgnoreExistingMailOnConnect(true)
       .OnMessageArrival(OnArrivalAsync)
       .IdleAsync();
}
catch (Exception ex)
{
    logger.LogError(ex, "An error occured while idling!");
}

async Task OnArrivalAsync(IMessageSummary messageSummary)
{
    try
    {
        var mimeMessage = await imapReceiver.ReadMail.GetMimeMessageAsync(messageSummary.UniqueId);
        logger.LogInformation("Arrived message! MessageId: {messageId} | UniqueId: {uniqueId}",
            mimeMessage.MessageId, messageSummary.UniqueId);
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "An error occured while handling arrived message!");
    }
}
```

Here's console output:

![image](https://user-images.githubusercontent.com/41568398/212496453-99eb0c30-7062-41da-b08b-29ad0446c25a.png)

**Comment by danzuep** [comment]
Hmm, I see what you're saying.

**Comment by danzuep** [comment]
Ah! Of course, the new folder reference doesn't know the idle folder has received new mail. A simple NoOp should fix that so I'll add that now.

**Comment by danzuep** [comment]
> ```cs
>     await imapReceiver.ConnectAuthenticatedImapClientAsync();
>     await imapReceiver.ConnectMailFolderAsync();
> ```

FYI you don't need the two lines above as `await imapReceiver.MonitorFolder...` does it for you. 🙂

**Comment by danzuep** [comment]
I've added another commit, thank God for CI/CD! Please test the latest version and let me know how it goes for you.

**Comment by q00Dree** [comment]
I just checked everything is working fine. Thanks!

But I'm interested in one more thing, the 'ReadMail' property creates a 'MailFolderReader' object every time I need to get a 'MimeMessage'. How will the garbage collector work in this case? Won't there be a lot of unnecessary objects in memory that have a reference to the 'ImapReceiver' through which they were created?

**Comment by danzuep** [comment]
That's great to hear! Thanks for finding the issue, I'll close the ticket then.

**Comment by danzuep** [comment]
As for the question about MailFolderReader not being disposable, your suggestion is correct! Thanks for spotting it, I started with a different design that didn't require disposal and forgot to add it when I changed to the current design. I'll add that now 🙂

**Comment by danzuep** [comment]
You're on a roll, any other suggestions? 😄

**Comment by q00Dree** [comment]
> You're on a roll, any other suggestions? 😄

I have to prepare for exams. In the middle of the week, I need to end the task associated with monitoring emails. Your code helped me a lot :)
