### ISSUE TITLE
MailFolderReader disposing 

### ISSUE THREAD

**Issue by q00Dree** [danzuep/MailKitSimplified#17]
Hi, @danzuep 

I've checked you implementation of **IAsyncDisposable** and **IDisposable** for **IMailFolderReader** and It seems to that  **DisposeAsync** should call **_imapReceiver?.DisposeAsync()** instead of [disconnecting](https://github.com/danzuep/MailKitSimplified/blob/main/source/MailKitSimplified.Receiver/Services/MailFolderReader.cs#L260) since **IImapReceiver** also implements **IAsyncDisposable** and **IDisposable**.

But my issue is not about that, It's more about design. The problem is still here. We can't dispose **ReadMail** this way. These objects are still being created and stored in memory. But If we will dispose **ReadMail** object after first read operation then we get **ObjectDisposedException** on the next call, because **_imapReceiver** will be disposed.

Therefore, you need to somehow create an **MailFolderReader** in the **ReadMail** property that will not refer to the main object **_imapReceiver** so that we can dispose of it after use.

Since that I prefer to create an **ImapClient** per message for fetching needed mime message by **UniqueId** from **IMessageSummary** object and after all dispose it.

```csharp
private async Task<IImapClient> CreateImapClientAsync()
{
    var imapClient = new ImapClient()
    {
        Timeout = (int)TimeSpan.FromMinutes(1).TotalMilliseconds
    };

    await imapClient.ConnectAsync(EmailClientConfiguration.ImapIp, EmailClientConfiguration.ImapPort);
    await imapClient.AuthenticateAsync(EmailClientConfiguration.Login, EmailClientConfiguration.Password);
    await imapClient.Inbox.OpenAsync(FolderAccess.ReadOnly);

    return imapClient;
}

private async Task OnArrivalAsync(IMessageSummary messageSummary)
{
    try
    {
        using var fetcher = await CreateImapClientAsync();
        var fetchedMessage = await fetcher.Inbox.GetMessageAsync(messageSummary.UniqueId, _cancel.Token);
        // do some processing things with fetched message
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "An error occured while handling arrived message with id: {uniqueId} for email client with id: {emailClientId}!",
            messageSummary.UniqueId.Id, EmailClientConfiguration.ClientId);
    }
}
```

**Comment by q00Dree** [comment]
Maybe it's worth implementing a object pool pattern. Create, let's say, 1 reader (can be configured) for concrete **ImapReceiver** and rent them.

**Comment by danzuep** [comment]
Thanks for spotting the DisposeAsync typo. Not quite sure what the issue is with the ObjectDisposedException though, it only happens on manual disposal which shouldn't really happen all that much. Can you give some examples using the library and associated logging?

**Comment by danzuep** [comment]
On first glance I thought you were talking about the cancellation exception, but on taking a second look I saw you said ObjectDisposedException. If you create the mail folder reader using the library then disposal is handled by the garbage collector. If you use the library based on the examples in the wiki then you should get a log file, please post it here.  https://github.com/danzuep/MailKitSimplified/wiki/Receiver

**Comment by danzuep** [comment]
There were multiple workarounds for this before which is why I haven't addressed it, but now I've released a change on the develop branch that should stop that from happening for you. If you'd be willing to test it that'd be really helpful.
