### ISSUE TITLE
How to connect STARTTLS enabled server?

### ISSUE THREAD

**Issue by mubassir-hasan** [danzuep/MailKitSimplified#19]
How can convert this configuration for ImapReceiver
```
            var client = new ImapClient();
            client.CheckCertificateRevocation = false;
            client.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13;
            client.ServerCertificateValidationCallback = (s, c, h, e) => true;
            client.Connect(item.IMAPHost, item.IMAPPort, MailKit.Security.SecureSocketOptions.StartTls);
            client.Authenticate(item.Email, item.IMAPPassword);
```

**Comment by danzuep** [comment]
If you're using the latest version then TLS is used by default if it is supported, but if you specifically want to disable SSL then the easiest way at the moment would be to pass your ImapClient in to the ImapReceiver constructor. Here's an example using IoC or Dependency Injection:
```cs
            services.AddTransient<IImapClient>((serviceProvider) => {
                var client = new ImapClient();
                client.CheckCertificateRevocation = false;
                client.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13;
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;
                return client;
            });
```

**Comment by danzuep** [comment]
Here's an simple example of how you'd do it without IoC or DI:
`new ImapReceiver(Options.Create(new EmailReceiverOptions()), logger, new LogFileWriter(), client, loggerFactory);`

**Comment by mubassir-hasan** [comment]
Thank you for your quick response. It worked like charm :). Feels dumb, Just another quick question where should I use this code background service!
Tried with .net core web project BackgroundService but not getting any updates. 
```
await imapReceiver.MonitorFolder
    .SetMessageSummaryItems().SetIgnoreExistingMailOnConnect()
    .OnMessageArrival((messageSummary) => OnArrivalAsync(messageSummary))
    .IdleAsync(cancellationToken);
```
Email server support idle connection checked with this code `_client.Capabilities.HasFlag(ImapCapabilities.Idle)`

**Comment by danzuep** [comment]
I've made an [example using a worker service](https://github.com/danzuep/MailKitSimplified/tree/main/samples/WorkerServiceExample) so read through that then let me know if you're still not sure.

**Comment by mubassir-hasan** [comment]
Thank you for **Simplified** solution

**Comment by danzuep** [comment]
Glad you like it @mubassir-hasan! To show your appreciation, please [star the repository](https://github.com/danzuep/MailKitSimplified) in the top right corner ⭐ 🌟 🤩
