### ISSUE TITLE
GetMessageSummariesAsync in v2.5.6 takes a long time

### ISSUE THREAD

**Issue by danzuep** [danzuep/MailKitSimplified#38]
GetMessageSummariesAsync method is slow in v2.5.6.

> https://github.com/danzuep/MailKitSimplified/issues/32#issuecomment-1723135408

**Comment by danzuep** [comment]
Thanks @faisalbwn for spotting this one. I've [deployed a new version](https://www.nuget.org/packages/MailKitSimplified.Receiver) so let me know how it goes.

**Comment by danzuep** [comment]
I've removed the slow result filtering from Range().GetMessageSummariesAsync() which fixes the issue. This means that Query().GetMessageSummariesAsync() now returns results in ascending order to match MailKit, so anyone relying on that will now need to use the Linq.Reverse() method to get results in descending order again.

**Comment by faisalbwn** [comment]
Thanks Daniel,
The fix is working fine for me.
