### ISSUE TITLE
Monitor multiple emails

### ISSUE THREAD

**Issue by Sylar-A** [danzuep/MailKitSimplified#39]
Hello!
How i can monitor inbox folders from more than 1 email (for example, 5)?
And how i can configure it in appsettings.json?

**Comment by danzuep** [comment]
I had some extra time today so I deployed an RC and added a [wiki section](https://github.com/danzuep/MailKitSimplified/wiki/MailFolder-Factories) specially for you 😄

**Comment by Sylar-A** [comment]
Thanks a lot! I'll test it later.

**Comment by danzuep** [comment]
I've released a new version for you: https://github.com/danzuep/MailKitSimplified/commit/0ece188a1927df55e12e4a53bc94b9012097f50a#commitcomment-127781496

**Comment by danzuep** [comment]
If you want to help the project then writing unit tests for the MailFolderMonitorFactory would be great.
