### ISSUE TITLE
ReplyTo Issue

### ISSUE THREAD

**Issue by faisalbwn** [danzuep/MailKitSimplified#40]
Dear,

I am constructing reply email as following:

```
MimeMessage replyMessage = await messageSummary.GetReplyMessageAsync(emailContent, true, true, true);
await _smtpSender.SendAsync(replyMessage);
```

But some how when i am receiving the email in my Outlook and try to reply, somehow it adds an extra email address in "To", which is "noreply@localhost". Can you highlight where i am going wrong.

Also the real requirement that in reply email content i need to add all of the previous email bodies as you can see in Outlook.

**Comment by danzuep** [comment]
The second reply example in the wiki shows how to set a reply address, otherwise it uses the configured value which defaults to noreply. https://github.com/danzuep/MailKitSimplified/wiki/Receiver#replying-to-emails

Did it not add all the previous email bodies? I'll check it tomorrow.

**Comment by danzuep** [comment]
The previous email body is there for me. 
![image](https://github.com/danzuep/MailKitSimplified/assets/82693586/5fa4685c-8329-470a-b0b4-5a715296a7fb)

Here's the code I used for testing, I've also specified "From" in the wiki now and added a new Top() method to just get the top result(s).
```cs
var replyMessage = mimeMessage
	.GetReplyMessage("Reply here.", addRecipients: false, replyToAll: false, includeMessageId: true, cancellationToken: cancellationToken)
	.From("from@localhost")
	.To("to@localhost");
```

**Comment by danzuep** [comment]
Please close this when you've got it working, or reply if you're seeing something different from me.
