### ISSUE TITLE
can support a dynamic template?

### ISSUE THREAD

**Issue by DreamTom** [danzuep/MailKitSimplified#51]
If I have a template but part of the content changes dynamically, can I support the rendering of dynamic templates? I think this feature can be added.

**Comment by danzuep** [comment]
What does the template use as a placeholder? Assuming it's an HTML template
and the placeholder is `{{FirstName}}`, the simplest option is to use the
Replace method to populate it from a variable.

**Comment by DreamTom** [comment]
thanks a lot, I found a good template rendering engine library called RazorEngineCore, which can help me implement some more complex templates

**Comment by danzuep** [comment]
Glad you found a solution, looks like a good library.
