### ISSUE TITLE
Having trouble moving mails

### ISSUE THREAD

**Issue by alasdair-richardson** [danzuep/MailKitSimplified#62]
I am trying to use MailKitSimplified to monitor an inbox, and try to process messages as they appear. Thi is wokring fine and was very easy to implement with MKS. What I want to do is move successfully processed messages to a Processed folder, but I can't seem to work out how to do it. Something like this

``` 
var mimeMessages = await imapReceiver.ReadMail
                    .GetMimeMessagesAsync(ct);
                foreach (var msg in mimeMessages)
                {
                    // Some code to parse and do stuff to the message
                    // Now it's parsed and dealt with, moce to Processed (summaries was fetched earlier to xref MessageId and uid)
                    var uid = GetUniueId(summaries, msg.MessageId);
                    if (uid != UniqueId.Invalid)
                    {
                        await imapReceiver.MailFolderClient.MoveToAsync(uid, "INBOX.Processed", ct);
                    }
```

But the last line always gives me the error
```
2024-05-15 10:23:56.3770 [ERROR] MailKitSimplified.Receive: mailserver.hostpresto.com alasdair@attar-richardson.com INBOX 10107 not moved to . MailKit.FolderNotOpenException: The folder is not currently open in read-write mode.
   at MailKit.Net.Imap.ImapFolder.CheckState(Boolean open, Boolean rw)
   at MailKit.Net.Imap.ImapFolder.MoveToAsync(IList`1 uids, IMailFolder destination, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.MailFolder.MoveToAsync(UniqueId uid, IMailFolder destination, CancellationToken cancellationToken)
   at MailKitSimplified.Receiver.Services.MailFolderClient.MoveOrCopyAsync(UniqueId messageUid, IMailFolder source, IMailFolder destination, Boolean move, CancellationToken cancellationToken)
```
I have tried opening the source and destination folders - but if I do that I open the source (it is open and connected ReadWrite) then the desitnation (open, readwrite) but after opening the destination folder the source is closed. It looks like in the MailKit code it should open the folders as necessary, but it always says 'not currently open in read-write mode', though I don't know which folder it is complaining about. I have also tried passing the opened destination folder to the MKS method which takes a folder, and just calling MoveToAsync on the source (INBOX) folder. Nothing seems to work, I must be doing somehting worng but no idea what.

**Comment by alasdair-richardson** [comment]
Not sure why the code is not formatting.. Will try 3 backticks instead of the code button
```
             var mimeMessages = await imapReceiver.ReadMail
                    .GetMimeMessagesAsync(ct);
                foreach (var msg in mimeMessages)
                {
                    // Parse and process the message
                    // Now it's parsed and dealt with, move to Processed
                    var uid = GetUniueId(summaries, msg.MessageId); // fetched earlier for xref msgId -> uid
                    if (uid != UniqueId.Invalid)
                    {
                        await imapReceiver.MailFolderClient.MoveToAsync(uid, "INBOX.Processed", ct);
                }
```

**Comment by alasdair-richardson** [comment]
PS just adding here in issues as Discussions seems to be empty and not sure where elks to ask for help ...

**Comment by danzuep** [comment]
"INBOX 10107 not moved to ." That means the destination is blank. Try "INBOX/Processed" 🙂

**Comment by danzuep** [comment]
Also there's an easier way of doing this that I forgot to put in the wiki, https://github.com/danzuep/MailKitSimplified/blob/4680ab7afd2edb8468e2bcc692448ca5b1815d84/source/MailKitSimplified.Receiver/Extensions/MessageSummaryExtensions.cs#L392

`await msg.MoveToAsync(destinationMailFolder, ct);`

**Comment by Sylar-A** [comment]
I did it this way:
```
    private async Task SendToArchiveAsync(IMessageSummary messageSummary)
    {
        IMailFolder archiveFolder;

        try
        {
            archiveFolder = await messageSummary.Folder.GetSubfolderAsync(_archiveFolderName);
        }
        catch (FolderNotFoundException)
        {
            archiveFolder = await messageSummary.Folder.CreateAsync(_archiveFolderName, isMessageFolder: true);
        }

        await messageSummary.MoveToAsync(archiveFolder);
    }
```
Because of it thows exception if you try to find subfolder that not exist.

**Comment by alasdair-richardson** [comment]
Thanks for your quick responses. I have to go out to play music now but will try these options first thing tomorrow and let you know if that is working ...

**Comment by danzuep** [comment]
Here's that translated into code (using parts of @Sylar-A's answer):
```cs
var destinationFolder = await GetOrCreateSubfolderAsync("INBOX/Processed", null, ct);
foreach (var msg in await imapReceiver.ReadMail.GetMimeMessagesAsync(ct))
{
    // Some code to parse and do stuff to the message
    await msg.MoveToAsync(destinationFolder, ct);
}

    async Task<IMailFolder> GetOrCreateSubfolderAsync(string mailFolderName, IMailFolder? baseFolder = null, CancellationToken cancellationToken = default)
    {
        if (baseFolder == null)
            baseFolder = _imapReceiver.ImapClient.Inbox;
        IMailFolder mailFolder;
        try
        {
            mailFolder = await baseFolder.GetSubfolderAsync(mailFolderName, cancellationToken);
        }
        catch (FolderNotFoundException)
        {
            mailFolder = await baseFolder.CreateAsync(mailFolderName, isMessageFolder: true, cancellationToken);
        }
        return mailFolder;
    }
```
I'll add that function to MailFolderClient in a future release 🙂

**Comment by alasdair-richardson** [comment]
I tried this solution this morning and it works beautifully, thanks for your help @danzuep and @Sylar-A. Incidentally Dan you suggested using folder INBOX/Processed instead of INBOX.Processed but that was what I first tried and I got MailKit.FolderNotFoundException: The requested folder could not be found. the one iwht the dot was in the list of folders returned by imapReceiver.GetMailFolderNamesAsync, so maybe my email provider does things differently. Anyway when i do this for real for the charity I am doing work for it will be on gmail which I suspect will be a whole other bundle of fun.

**Comment by alasdair-richardson** [comment]
PS thanks for providing this great library.

**Comment by alasdair-richardson** [comment]
Actually looking more closely at your solution I see you are calling MoveToAsync on the MimeMessage rather than the summary - but that does not appear to have that method? At least in the version I am using which seems to be 4.5.0.

**Comment by danzuep** [comment]
Here's the latest version of this library: https://github.com/danzuep/MailKitSimplified/releases

I've fixed my post, getting the folder once is much more efficient than getting it every single time a new email comes in.

**Comment by danzuep** [comment]
> PS thanks for providing this great library.

Please star the repository to show your thanks!
