### ISSUE TITLE
GetMimeMessageAsync Removed

### ISSUE THREAD

**Issue by faisalbwn** [danzuep/MailKitSimplified#65]
Dear @danzuep ,

I updated the version from NuGet and no more find the GetMimeMessageAsync  in newer version as follows:

// Fetch email message against presisted uid
MimeMessage mimeMessage = await _imapReceiver.ReadMail.**GetMimeMessageAsync**(new UniqueId(uniqueId), cancellationToken);

**Comment by danzuep** [comment]
It had this attribute on it for a while before it was removed in [this commit](https://github.com/danzuep/MailKitSimplified/commit/2f864a8256bcbfb9e17baf13fe95b793171e1c5e#diff-b34d62c7416b86c953048a9758b48ac14d161a48106e0e1ec57d4fcc787eb23aL29): `[Obsolete("Use Range(uniqueId).GetMimeMessagesAsync() instead.")]`. I should have waited for a major version change to remove it though, my bad.

**Comment by danzuep** [comment]
Here's the [updated method](https://github.com/danzuep/MailKitSimplified/blob/ce6f0c70e2195361260a6d7837343106cfa9a58b/source/MailKitSimplified.Receiver/Services/MailFolderReader.cs#L91): `await imapReceiver.ReadMail.Range(uniqueId)
    .GetMimeMessagesAsync(cancellationToken);`
