### ISSUE TITLE
Folders (or Labels) in Google mail

### ISSUE THREAD

**Issue by alasdair-richardson** [danzuep/MailKitSimplified#68]
I raised an issue previously about trying to move emails from INBOX to a _Processed_ folder. The suggestions all worked fine when I was trying it out on my own mail server. However the charity i am doing the work for use google mail. From all I have read online google do not really have folders, they have labels. On the web I created a Processed label and moved some emails into it and that all seemed to work. Apparently google use imap calls for folders to control labels. But I can;t seem to make it work.
First I am getting a list of all the folders, Processed does not appear. 
```
2024-06-21 14:09:30.3663 [DEBUG] MailKitSimplified.Receive: 0 Inbox folders: . 
2024-06-21 14:09:31.3216 [DEBUG] MailKitSimplified.Receive: 7 personal folders: All Mail, Bin, Drafts, Important, Sent Mail, Spam, Starred.
```
I am trying to get hold of the folder using
```
            var destination = await summary.Folder.GetSubfolderAsync("Processed", ct);
```
and getting an exception as folder not found. The same happens if I try _Spam_. So really the question is how do I do this with Google?

**Comment by alasdair-richardson** [comment]
Sorry trying to work out how to label as a question

**Comment by alasdair-richardson** [comment]
Actually just saw the wiji section on folders, looks like maybe this would work - If I update to a later version than 2.10.0. Would that be correct?
```
var mailFolder = await _imapReceiver.MailFolderClient.GetFolderAsync([mailFolderName], cancellationToken);
```

**Comment by danzuep** [comment]
Yes, try the second method and let me know how it goes 🙂

**Comment by alasdair-richardson** [comment]
Will do. I just tried the method suggested on that wiki page for 2.10.0 (Option 5, GetOrCreateFolderAsync) and it did not work. Had to fix the example code - do you want me to do that on the wiki? (missing var, no return)

**Comment by danzuep** [comment]
If you can edit it, please do! If not then post it here and I'll update it.

**Comment by alasdair-richardson** [comment]
Oh ok i don't think I can edit so here
```
public async Task<IMailFolder> GetOrCreateFolderAsync(string mailFolderName, CancellationToken cancellationToken = default)
{
    var client = _imapReceiver.ImapClient;
    var baseFolder = client.GetFolder(client.PersonalNamespaces[0]);
    var folder = baseFolder.GetSubfolders(false, CancellationToken.None).FirstOrDefault(x =>
        mailFolderName.Equals(x.Name, StringComparison.OrdinalIgnoreCase));
    try
    {
        folder ??= await client.GetFolderAsync(mailFolderName, cancellationToken).ConfigureAwait(false);
    }
    catch (FolderNotFoundException)
    {
        folder = await baseFolder.CreateAsync(mailFolderName, isMessageFolder: true, cancellationToken);
    }
    return folder;
}
```

-- added var before folder and a return at the bottom

**Comment by danzuep** [comment]
Thanks! I actually made multiple mistakes with that one as I didn't test it properly, I'll add a tested method here as that folder still won't be open sorry.

**Comment by danzuep** [comment]
If you download the pre-release from NuGet you can use this: `var folder = await mailFolderClient.GetOrCreateFolderAsync(destinationFolderFullName, cancellationToken);`

**Comment by alasdair-richardson** [comment]
And as regards moving to a different folder in Google. no joy so far. My _Processed_ label does not appear in the list obtained from `await imapReceiver.GetMailFolderNamesAsync(ct);` but Spam does, so I have been trying to get hold of that using `await imapReceiver.MailFolderClient.GetFolderAsync([folder], ct);`. this does not work (I just get null) for _Processed_, _Spam_ and _[Gmail]/Spam_. ([this link](https://developers.google.com/gmail/imap/imap-extensions) seemed to suggest that [Gmail]/Spam might be recognised). 
No idea what to do next. Why does Gmail have to be different?

**Comment by danzuep** [comment]
Maybe create the new folder manually in Gmail, then use `await mailFolderClient.MoveToAsync(messageSummary, _archiveFolderName);`

**Comment by danzuep** [comment]
It's for a charity right? I should have some time to look at it tomorrow 🙂

**Comment by alasdair-richardson** [comment]
Yes I can try a couple of things tomorrow. Have to go out and play some music now. And yes I am doing the work for a charity - Campaign against Antisemitism. An online system for onboarding volunteers and then managing them. I am retired but still seem to keep pretty busy, and this is a lot more interesting than WordPress!

**Comment by danzuep** [comment]
Seems there is [no easy way](https://stackoverflow.com/questions/37939895/is-there-any-way-to-retrieve-labels-or-folder-id-in-imap-mailkit#comment63391944_37950760) to get all Gmail labels. The good news though is that you don't need to!
Download the [latest pre-release version](https://www.nuget.org/packages/MailKitSimplified.Receiver), then use this to create a "Processed" label in Gmail:
`var mailFolder = await mailFolderClient.GetOrCreateFolderAsync(mailFolderFullName, cancellationToken);`
Once you've made the label you just move it like this:
`var uniqueId = await mailFolderClient.MoveToAsync(messageSummary, destinationFolderFullName, cancellationToken);`

**Comment by alasdair-richardson** [comment]
Wow that's great thanks a lot. I just have a meeting with the guy from CAA but I will try this out afterwards.

**Comment by alasdair-richardson** [comment]
Yes I can confirm this is working. Thanks again.
