### ISSUE TITLE
Add a handler for the `IMailFolder.MessageFlagsChanged` event

### ISSUE THREAD

**Issue by danzuep** [danzuep/MailKitSimplified#73]
Hi, great library!
Perhaps something that is missing is being able to listen to flag changes on emails.

If I set up my monitor as such:
`await _imapReceiverClient.MonitorFolder
    .SetMessageSummaryItems()
    .SetIgnoreExistingMailOnConnect()
    .OnMessageArrival(OnArrivalAsync)
    .IdleAsync(_cancel.Token);`
    
There doesn't appear to be an extension method or handler for the `IMailFolder.MessageFlagsChanged` event.

Are there any plans to add this or have I missed something obvious?

_Originally posted by @mabeale in https://github.com/danzuep/MailKitSimplified/discussions/67#discussioncomment-10416605_

**Comment by danzuep** [comment]
I've added this feature and submitted a preview release, enjoy!

**Comment by mabeale** [comment]
Thanks for that!

The event fires off but it looks like it is sending the MessageSummary for its initial state. I.e. if the process starts and there is a **read** email in the inbox then no matter how many times I change it to **unread** and back to **read**, the MessageSummary is still showing it as **read**.
Conversely, if I start the process with an **unread** email in the inbox, and changes to its flag will also show as **unread**.

I think the issue could be that it is returning the email from a cached list of emails from when the process first starts.
Is there a way for you to re-read the email before returning it?

**Comment by danzuep** [comment]
Good point, I've added you suggestion.

**Comment by danzuep** [comment]
It may not work for the scenario where you want to ignore any read emails in the inbox but process them once they become unread. Feel free to make a pull request to add that functionality, but let me know you're working on it so I don't double-up.

**Comment by mabeale** [comment]
Wow, thanks a lot. Is it possible to create a nuget package for that update?

It might work as it is as this is my approach:

`
public async Task MonitorInbox()
{
    await _imapReceiverClient.MonitorFolder
        .SetMessageSummaryItems(MessageSummaryItems.All)
        .SetIgnoreExistingMailOnConnect(false)
        .OnMessageArrival(OnArrivalAsync)
        .OnMessageFlagsChanged(OnMessageFlagsChangedAsync)
        .IdleAsync(_cancel.Token);
}
        
private async Task OnArrivalAsync(IMessageSummary messageSummary)
{
    if (messageSummary == null || messageSummary.Flags.HasValue && messageSummary.Flags.Value.HasFlag(MessageFlags.Seen)) 
    {
        Trace.TraceInformation("The email object was null or the email has already been read. Processing stopped.");
        return;
  }
  .....
}`

**Comment by danzuep** [comment]
Ah, the pipeline passed so I thought it was published. Here's a another one: https://www.nuget.org/packages/MailKitSimplified.Receiver/2.11.12-tags-v2-11-12-rc0001

**Comment by mabeale** [comment]
Great, thanks a lot! It's working wonderfully! I really appreciate the quick turnaround!
