### ISSUE TITLE
Code duplication for sending mails

### ISSUE THREAD

**Issue by rklec** [danzuep/MailKitSimplified#76]
E.g. the send method here:

https://github.com/danzuep/MailKitSimplified/blob/789a4d695e2dabeaa6c57db5982632dfab656b9f/source/MailKitSimplified.Email/Services/SmtpSender.cs#L128-L136

and here:
https://github.com/danzuep/MailKitSimplified/blob/789a4d695e2dabeaa6c57db5982632dfab656b9f/source/MailKitSimplified.Sender/Services/SmtpSender.cs#L340-L352

...is really quite duplicated.

Generally, why do two places duplicate code for ending mails, this might be refactored...

**Comment by danzuep** [comment]
MailKitSimplified.Email was meant to be version 2.0 of this library. It should probably be in a separate branch, but the benefit of having it here is that it makes it easier to apply fixes to both versions at the same time. I lost much of my free time though so it'll be a while before I finish cleaning it up.
