### ISSUE TITLE
How do I use IdleAsync?

### ISSUE THREAD

**Issue by Avrohom** [danzuep/MailKitSimplified#79]
I have tried the `imapReceiver.MonitorFolder.IdleAsync`. It is not working. 

Than, I have followed the Idle example from the MailKit documention on the very same Imap server with same credentials and it did work.

**Comment by danzuep** [comment]
Hi Avrohom, if you got the MailKit one working, then great! If you want to test this one though, try some of the [examples](https://github.com/danzuep/MailKitSimplified/blob/main/samples/ConsoleServiceExample/Program.cs) in the samples folder. If you're using Visual Studio, you can right click the project and use the built-in UserSecrets provider to log in.
