### ISSUE TITLE
multi-sending

### ISSUE THREAD

**Issue by SyntaxEvg** [danzuep/MailKitSimplified#8]
Hello, does your product support multi-sending mail to clients? abs@gmail.com;absd@gmail.com

**Comment by danzuep** [comment]
Hi @SyntaxEvg, yes it does. You can either use `smtpSender.WriteEmail.To("abs@gmail.com;bsd@gmail.com")` or `smtpSender.WriteEmail.To("abs@gmail.com").To("bsd@gmail.com")`.
