### ISSUE TITLE
How do I tag and delete messages?

### ISSUE THREAD

**Issue by xiongliu666** [danzuep/MailKitSimplified#9]
How do I tag and delete messages?

**Comment by danzuep** [comment]
Hi @xiongliu666, [MailKit](https://github.com/jstedfast/MailKit#deleting-messages-in-imap) has that functionality built-in. Here's how to do it:
```csharp
imapClient.Inbox.AddFlags(uniqueIds, MessageFlags.Deleted);
imapClient.Inbox.Expunge();
```

**Comment by danzuep** [comment]
Here's how to delete the first message in the Inbox:
```csharp
var mailFolder = await imapReceiver.ConnectMailFolderAsync();
var messageSummaries = await imapReceiver.ReadMail.Take(1).GetMessageSummariesAsync();
var uniqueId = filteredSummaries.Single().UniqueId;
await mailFolder.AddFlagsAsync(uniqueId, MessageFlags.Deleted, silent: true);
await mailFolder.ExpungeAsync();
```
I've added this to the [wiki](https://github.com/danzuep/MailKitSimplified/wiki/Receiver/_edit#message-flags).
